version: '3.6'
services:
  nginx: 
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - shop_service
      - retailer_service
      - manufacture_service
    networks:
      - backend

  shop_service:
    container_name: shop_service
    build:
      context: shop_service/
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5001:5000"
    volumes:
      - ./shop_service:/code
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      SECRET_KEY: debug_key
      # SQLALCHEMY_DATABASE_URI: mysql+pymysql://admin:whatever@database/retailer_data
      SQLALCHEMY_DATABASE_URI: sqlite:///data.sqlite3
    depends_on:
      - database
    networks:
      - backend

  retailer_service:
    container_name: retailer_service
    build:
      context: retailer_service/
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5002:5000"
    volumes:
      - ./retailer_service:/code
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      SECRET_KEY: debug_key
      # SQLALCHEMY_DATABASE_URI: mysql+pymysql://admin:whatever@database/retailer_data
      SQLALCHEMY_DATABASE_URI: sqlite:///data.sqlite3
    depends_on:
      - database
    networks:
      - backend

  manufacture_service:
    container_name: manufacture_service
    build:
      context: manufacture_service/service
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5003:5000"
    volumes:
      - ./manufacture_service/service:/code
      - ./manufacture_service/manager:/code/manager
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      SECRET_KEY: debug_key
      # SQLALCHEMY_DATABASE_URI: mysql+pymysql://admin:whatever@database/retailer_data
      SQLALCHEMY_DATABASE_URI: sqlite:///data.sqlite3
    depends_on:
      - database
      - celery
    networks:
      - backend

  celery:
    container_name: celery
    build:
      context: manufacture_service/manager
      dockerfile: Dockerfile
    volumes:
      - ./manufacture_service/manager:/code
    depends_on:
      - rabbit
    networks:
      - backend

  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=whatever
    ports:
      - "5672:5672"
    networks:
      - backend

  database: 
    image: mysql
    container_name: database
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
        - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=whatever
      - MYSQL_ROOT_PASSWORD=banana
    networks:
      - backend

networks:
  backend:
    name: backend
