version: '3.6'
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - shop_service
      - retailer_service
      - manufacture_service
    networks:
      - backend

  shop_service:
    container_name: shop_service
    build:
      context: shop_service/
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./shop_service:/code
    environment:
      FLASK_ENV: development
    networks:
      - backend

  retailer_service:
    container_name: retailer_service
    build:
      context: retailer_service/
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./retailer_service:/code
    environment:
      FLASK_ENV: development
    networks:
      - backend

  manufacture_service:
    container_name: manufacture_service
    build:
      context: manufacture_service/service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./manufacture_service:/code
      - ./celery/app/proj:/code/proj
    environment:
      FLASK_ENV: development
    networks:
      - backend

  celery:
    container_name: celery
    build:
      context: manufacture_service/manager/
      dockerfile: Dockerfile
    volumes:
      - ./celery/app:/app
    depends_on:
      - rabbit
    networks:
      - backend

  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=whatever
    ports:
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    name: backend
